export const DEFAULT_THEME_NAME = 'ascTheme'
export { default as brakpoints } from './breakpoints'
export { default as colors } from './colors'
export { default as globalStyle } from './globalStyle'
export { default as typography } from './typography'
