version: 2
updates:
- package-ecosystem: npm
  directory: "/examples/create-react-app"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - examples
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/examples/nextjs"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - examples
