version: 2
updates:
- package-ecosystem: npm
  directory: "/examples/create-react-app"
  schedule:
    interval: weekly
  labels:
  - dependencies
  - examples
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: npm
  directory: "/examples/nextjs"
  schedule:
    interval: weekly
  labels:
  - dependencies
  - examples
