sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - '10'
  - '12'
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn lint
  - yarn test
  - yarn build-storybook
branches:
  only:
    - master
deploy:
  local_dir: .sb
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
