sudo: false
os:
  - linux
language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn lint
  - yarn test
  - yarn build:storybook
branches:
  only:
    - master
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
  - provider: pages
    local_dir: ./stories/lib
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
      node: '12'
      os: linux
  - provider: script
    script: yarn publish:canary
    skip_cleanup: true
    on:
      branch: master
      node: '12'
      os: linux
