sudo: false
os:
  - linux
  - windows
  - osx
language: node_js
node_js:
  - '12'
  - '10'
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn lint
  - yarn test --maxWorkers=4
  - yarn build
branches:
  only:
    - master
