"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    fill: [
        'alert',
        'announcement',
        'calendar',
        'card',
        'checkmark',
        'chevron-down',
        'chevron-left',
        'chevron-right',
        'chevron-top',
        'close',
        'document-text',
        'document',
        'download',
        'eclipse',
        'email',
        'embed',
        'enlarge-font',
        'enlarge',
        'environment',
        'external-link',
        'facebook-padded',
        'facebook',
        'linkedin',
        'login',
        'logo-short',
        'logo-tall',
        'logout',
        'menu',
        'minimise',
        'opening-hours',
        'passport',
        'print',
        'quote',
        'search',
        'trash-bin',
        'twitter'
    ],
    outline: [],
    twotone: []
};
