// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const Alert: IconDefinition = {
  name: 'alert',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 36 36' },
    children: [
      {
        tag: 'path',
        attrs: { d: 'M33.63 30.9H2.37L18 3zm-24.44-4h17.62L18 11.19z' }
      },
      { tag: 'path', attrs: { d: 'M17 16.99h2v4.95h-2zM17 22.94h2v1.95h-2z' } }
    ]
  }
};

export default Alert;
