// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const Calendar: IconDefinition = {
  name: 'Calendar',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 36 36' },
    children: [
      {
        tag: 'path',
        attrs: { d: 'M28 6V2h-4v4H12V2H8v4H2v28h32V6zm2 24H6V14h24z' }
      },
      {
        tag: 'path',
        attrs: {
          d:
            'M10 17h4v4h-4zM16 17h4v4h-4zM22 17h4v4h-4zM10 23h4v4h-4zM16 23h4v4h-4z'
        }
      }
    ]
  }
};

export default Calendar;
