// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const Checkmark: IconDefinition = {
  name: 'checkmark',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: { d: 'M12.22 27.02L0 14.17l2.91-2.77 9.35 9.83L29.13 4 32 6.8z' }
      }
    ]
  }
};

export default Checkmark;
