// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const ChevronRight: IconDefinition = {
  name: 'chevron-right',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: { d: 'M9.76 32l-2.9-2.91L19.94 16 6.86 2.91 9.76 0l16 16z' }
      }
    ]
  }
};

export default ChevronRight;
