// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const ChevronDown: IconDefinition = {
  name: 'ChevronDown',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: { d: 'M16 25.76l-16-16 2.91-2.9L16 19.94 29.09 6.86 32 9.76z' }
      }
    ]
  }
};

export default ChevronDown;
