// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const ChevronLeft: IconDefinition = {
  name: 'chevron-left',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: { d: 'M22.86 32l-16-16 16-16 2.9 2.91L12.68 16l13.08 13.09z' }
      }
    ]
  }
};

export default ChevronLeft;
