// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const ChevronTop: IconDefinition = {
  name: 'chevron-top',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: { d: 'M29.09 25.76L16 12.68 2.91 25.76 0 22.86l16-16 16 16z' }
      }
    ]
  }
};

export default ChevronTop;
