// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const Close: IconDefinition = {
  name: 'Close',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M29.33 5.47l-2.8-2.8L16 13.19 5.47 2.67l-2.8 2.8L13.19 16 2.67 26.53l2.8 2.8L16 18.81l10.53 10.52 2.8-2.8L18.81 16z'
        }
      }
    ]
  }
};

export default Close;
