// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const DocumentText: IconDefinition = {
  name: 'DocumentText',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 36 36' },
    children: [
      { tag: 'path', attrs: { d: 'M12 16h12v2H12z' } },
      {
        tag: 'path',
        attrs: { d: 'M21.83 2H6v32h24V10.17zM10 30V6h10.17L26 11.83V30z' }
      },
      { tag: 'path', attrs: { d: 'M12 20h12v2H12zM12 24h12v2H12z' } }
    ]
  }
};

export default DocumentText;
