// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const Document: IconDefinition = {
  name: 'document',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 36 36' },
    children: [
      {
        tag: 'path',
        attrs: { d: 'M21.83 2H6v32h24V10.17zM10 30V6h10v6h6v18z' }
      }
    ]
  }
};

export default Document;
