// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const Download: IconDefinition = {
  name: 'download',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M0 28h32v4H0v-4zM22.36 14l2.83 2.83-9.19 9.2-9.19-9.2L9.64 14 14 18.38V0h4v18.38L22.36 14z'
        }
      }
    ]
  }
};

export default Download;
