// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const Eclipse: IconDefinition = {
  name: 'eclipse',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 1024 1024' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M784 565.6H675.4V457H784v108.6zm-217.2 0H458.2V457h108.6v108.6zm-218.2 0H240V457h108.6v108.6z'
        }
      }
    ]
  }
};

export default Eclipse;
