// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const Email: IconDefinition = {
  name: 'Email',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M0 4v24h32V4H0zm16.12 12.33L6 8h20.06l-9.94 8.33zM11.33 15L4 21.78V8.94L11.33 15zm1.56 1.28l3.24 2.67 3.08-2.58L27.45 24H4.55l8.34-7.72zm7.87-1.2L28 9v12.8l-7.24-6.72z'
        }
      }
    ]
  }
};

export default Email;
