// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const Enlarge: IconDefinition = {
  name: 'enlarge',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      { tag: 'path', attrs: { d: 'M32 14H18V0h-4v14H0v4h14v14h4V18h14z' } }
    ]
  }
};

export default Enlarge;
