// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const ExternalLink: IconDefinition = {
  name: 'ExternalLink',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M19 0h13.01v13h-4V6.82L14.43 20.42 11.6 17.6 25.2 4H19V0zm7 14l.02 18H0V6.02h17.98L14 9.99l.02.02h-10v18h18L22 17.98l4-4z'
        }
      }
    ]
  }
};

export default ExternalLink;
