// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const Facebook: IconDefinition = {
  name: 'Facebook',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 30 30' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M24.5 18.13l.64-4.61h-4.77v-2.97c0-1.33.42-2.25 2.33-2.25h2.55V4.2c-.42-.1-1.91-.2-3.71-.2-3.71 0-6.15 2.15-6.15 6.14v3.38h-4.14v4.6h4.14V30h4.98V18.13h4.14z'
        }
      }
    ]
  }
};

export default Facebook;
