// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const FacebookPadded: IconDefinition = {
  name: 'FacebookPadded',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 1024 1024' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M667.7 541.1l15.88-119.05H564.53v-76.73c0-34.4 10.58-58.2 58.2-58.2h63.5V181.29c-10.58-2.64-47.62-5.29-92.6-5.29-92.6 0-153.45 55.56-153.45 158.74v87.3H337V541.1h103.18V848h124.35V541.1H667.7z'
        }
      }
    ]
  }
};

export default FacebookPadded;
