// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const Logout: IconDefinition = {
  name: 'logout',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 36 36' },
    children: [
      { tag: 'path', attrs: { d: 'M16 6V2H2v32h14v-4H6V6h10z' } },
      {
        tag: 'path',
        attrs: {
          d:
            'M24.82 8.81L22 11.64 26.36 16H8v4h18.36L22 24.36l2.82 2.83 9.2-9.19-9.2-9.19z'
        }
      }
    ]
  }
};

export default Logout;
