// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const Menu: IconDefinition = {
  name: 'menu',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M0 3.24h32V7.8H0V3.24zM0 13.7h32v4.58H0V13.7zM0 24.2h32v4.57H0V24.2z'
        }
      }
    ]
  }
};

export default Menu;
