// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const Minimise: IconDefinition = {
  name: 'Minimise',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [{ tag: 'path', attrs: { d: 'M0 13.71h32v4H0z' } }]
  }
};

export default Minimise;
