// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const Passport: IconDefinition = {
  name: 'passport',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 36 36' },
    children: [
      {
        tag: 'path',
        attrs: { d: 'M24 26v-1c0-3-1.7-4-4-4h-4c-2.31 0-4 1-4 4v1z' }
      },
      { tag: 'circle', attrs: { cx: '18', cy: '17.01', r: '2.99' } },
      { tag: 'path', attrs: { d: 'M26 6V2L5 6v28h26V6zm1 24H9V10h18z' } }
    ]
  }
};

export default Passport;
