// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const Quote: IconDefinition = {
  name: 'Quote',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M0 13.1v-2.03l5.07-5.04L5.05 6h3.12v7.1H14V27H0V13.1zm18 0v-2.03l5.08-5.04-.03-.03h3.12v7.1H32V27H18V13.1z'
        }
      }
    ]
  }
};

export default Quote;
