// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const Search: IconDefinition = {
  name: 'Search',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M32 29.12l-9.82-9.83a12.22 12.22 0 1 0-2.89 2.89L29.12 32 32 29.12zm-19.77-8.75a8.14 8.14 0 1 1 0-16.29 8.14 8.14 0 0 1 0 16.3z'
        }
      }
    ]
  }
};

export default Search;
