// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const TrashBin: IconDefinition = {
  name: 'TrashBin',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 36 36' },
    children: [
      {
        tag: 'path',
        attrs: {
          d: 'M31 6h-8V2H13v4H5v4h2v24h22V10h2zM15 4h6v2h-6zm10 26H11V10h14z'
        }
      },
      {
        tag: 'path',
        attrs: {
          d: 'M13.02 14H15v12h-1.98zM17 14h2v12h-2zM21.02 14H23v12h-1.98z'
        }
      }
    ]
  }
};

export default TrashBin;
