// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from './types';

const Twitter: IconDefinition = {
  name: 'Twitter',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M10.17 29c12.07 0 18.58-10.13 18.58-18.75v-.82A12.97 12.97 0 0 0 32 6.01c-1.22.55-2.44.82-3.8 1.1a6.02 6.02 0 0 0 2.85-3.7 11.27 11.27 0 0 1-4.2 1.64A6.63 6.63 0 0 0 22.1 3a6.54 6.54 0 0 0-6.5 6.57c0 .55 0 .96.13 1.5A18.25 18.25 0 0 1 2.3 4.23c-.55.69-.82 1.92-.82 3.15a6.68 6.68 0 0 0 2.85 5.47 5.77 5.77 0 0 1-2.98-.82v.14c0 3.15 2.3 5.88 5.28 6.43-.54.14-1.08.27-1.76.27-.4 0-.81 0-1.22-.13a6.75 6.75 0 0 0 6.1 4.65 13.1 13.1 0 0 1-8.13 2.87c-.55 0-1.09 0-1.63-.13A19.61 19.61 0 0 0 10.17 29'
        }
      }
    ]
  }
};

export default Twitter;
