version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
    ignored_updates:
      - match:
          dependency_name: "jest-styled-components"
      - match:
          dependency_name: "styled-components"
