version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"

  - package_manager: "javascript"
    directory: "/examples/create-react-app"
    update_schedule: "daily"
    default_labels:
      - dependencies
      - examples

  - package_manager: "javascript"
    directory: "/examples/nextjs"
    update_schedule: "daily"
    default_labels:
      - dependencies
      - examples

  - package-manager: "github-actions"
    directory: "/"
    update_schedule: "daily"