export const DEFAULT_THEME_NAME = 'default'
export { default as breakpoint } from './breakpoint'
export { default as colors } from './colors'
export { default as globalStyle } from './globalStyle'
export { default as typography } from './typography'
export { default as spacing } from './spacing'
