name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Set up Node 12
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn lint
    - run: yarn test
    - run: yarn build:storybook
    - name: Publish canary version
      if: github.ref == 'refs/heads/master'
      run: |
        echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        yarn publish:canary
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Deploy to Github pages
      uses: JamesIves/github-pages-deploy-action@3.5.9
      if: github.ref == 'refs/heads/master'
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: stories/lib
