name: Publish canary to NPM

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Fetch all history for all tags and branches (needed for lerna / semantic release to correctly version)
        fetch-depth: 0
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: install
      run: yarn install --frozen-lockfile

    - name: build
      run: yarn build

    - name: Publish canary to NPM
      run: |
        echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        yarn publish:canary
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}